### ISSUE TITLE
Repetition does not work correctly?

### ISSUE THREAD

**Issue by quicknir** [wcsmith/evil-args#6]
I'm finding that things like 3daa do not work, even though hitting daa and then hitting . twice will work.

**Comment by braham-snyder** [comment]
for what it's worth, 3dL, e.g., (or whatever you bind evil-forward-arg to) does work

**Comment by wcsmith** [comment]
Sorry I haven't been responsive on this repo. Should work now (for searching forward at least). Let me know if you have any problems.
