### ISSUE TITLE
Wrong behavior with C style pointers

### ISSUE THREAD

**Issue by moshohayeb** [wcsmith/evil-args#9]
Evil-args seems to consider '>' as an argument separator

Reproduce steps
```
housekeep(timer->epoch, arg1, arg2, arg3);

// cursor at timer->|epoch 
// cia

// Expected output
housekeep(|, arg1, arg2, arg3);

// Actual output
|, arg1, arg2, arg3);
```

**Comment by wcsmith** [comment]
I can't seem to repro this (I get your expected output).

What are the values of evil-args-delimiters, evil-args-closers, evil-args-openers for you?

Can find these with: M-x eval-expression <ret> evil-args-delimiters <ret>

**Comment by moshohayeb** [comment]
These are the value for evil-args-delimiters

("," ";")

p.s. I am using [Doom](https://github.com/hlissner/doom-emacs/)

**Comment by moshohayeb** [comment]
Ok turns out it was indeed an issue with Doom

Apologies and closing.
